apiVersion: v1
kind: Service
metadata:
  name: {{ include "webgoat.fullname" . }}
  labels:
    {{- include "webgoat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: webgoat
  selector:
    {{- include "webgoat.selectorLabels" . | nindent 4 }}
